In [1]:
import os
import sys

In [2]:
import pandas as pd

In [3]:
module_path = os.path.abspath(os.path.join('..'))
if module_path not in sys.path:
    sys.path.insert(0, module_path)

In [4]:
from spectroscopy.utils import DATA_DIR, parse_abs_files

# load in ABS files

In [5]:
dfs = [pd.read_csv(filename) for filename in DATA_DIR.glob('*.ABS')]

In [6]:
len(dfs)

96

# explore one file

In [7]:
df = dfs[0]

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 510 entries, 0 to 509
Data columns (total 1 columns):
 #   Column                                                                                                                                                               Non-Null Count  Dtype
---  ------                                                                                                                                                               --------------  -----
 0    File: Users\stell\Desktop\StellarDat\South 18
  ABSOR->  Wave:1277.42nm  Pix:248  Val:  0.180  Time: 40ms  Avg:10  Sm:2  Sg:0  Tc:off  SNAP  Xt:3  Ch:1  Xtrig    510 non-null    object
dtypes: object(1)
memory usage: 4.1+ KB

In [9]:
df.head()

   File: Users\stell\Desktop\StellarDat\South 18 \r\n  ABSOR->  Wave:1277.42nm  Pix:248  Val:  0.180  Time: 40ms  Avg:10  Sm:2  Sg:0  Tc:off  SNAP  Xt:3  Ch:1  Xtrig
0                                862.13  1.0000E-003
1                                863.88  1.0000E-003
2                                865.63  1.0000E-003
3                                867.38  7.4608E-004
4                                869.13  0.0000E+000

looks like these files are the same exact fromat as the .TRM files, so we can reuse the parser!

In [12]:
df_abs = parse_abs_files()

In [13]:
df_abs.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 96 entries, 0 to 0
Columns: 516 entries, 862.13 to process_method
dtypes: datetime64[ns](1), float64(510), object(5)
memory usage: 387.8+ KB

In [15]:
df_abs.describe()

,862.13,863.88,865.63,867.38,869.13,870.88,872.63,874.38,876.13,877.88,...,1737.13,1738.88,1740.63,1742.38,1744.13,1745.88,1747.63,1749.38,1751.13,1752.88
count,9.600000e+01,9.600000e+01,9.600000e+01,96.000000,96.000000,96.000000,96.000000,96.000000,96.000000,96.000000,...,96.000000,96.000000,96.000000,96.000000,96.000000,96.000000,96.000000,96.000000,96.000000,96.000000
mean,1.000000e-03,1.000000e-03,1.000000e-03,0.003866,0.015204,0.105489,0.226209,0.210638,0.213721,0.226898,...,0.270371,0.269513,0.268529,0.267405,0.266427,0.265755,0.265239,0.264634,0.263894,0.262948
std,2.179787e-19,2.179787e-19,2.179787e-19,0.078384,0.293815,0.200905,0.069105,0.067286,0.067480,0.069031,...,0.081136,0.080985,0.080700,0.080277,0.079968,0.079852,0.079831,0.079732,0.079554,0.079253
min,1.000000e-03,1.000000e-03,1.000000e-03,-0.151080,-0.647130,-0.336540,0.113730,0.102600,0.104370,0.113570,...,0.134880,0.134050,0.133230,0.132400,0.131530,0.131150,0.130980,0.130710,0.130320,0.130040
25%,1.000000e-03,1.000000e-03,1.000000e-03,0.000746,0.000000,0.072645,0.178043,0.164220,0.167063,0.177567,...,0.215825,0.215125,0.214572,0.213680,0.213052,0.212455,0.211580,0.210810,0.210760,0.209820
50%,1.000000e-03,1.000000e-03,1.000000e-03,0.000746,0.000000,0.096868,0.214455,0.198620,0.202510,0.214605,...,0.253310,0.252740,0.252285,0.251605,0.250740,0.250225,0.249970,0.249345,0.248525,0.247560
75%,1.000000e-03,1.000000e-03,1.000000e-03,0.000746,0.000000,0.135535,0.249023,0.230372,0.234508,0.250170,...,0.302803,0.302125,0.301090,0.299720,0.298475,0.297900,0.297723,0.297070,0.296315,0.295120
max,1.000000e-03,1.000000e-03,1.000000e-03,0.489260,1.273900,0.909370,0.449950,0.434330,0.438800,0.457490,...,0.520900,0.517180,0.514910,0.513910,0.512740,0.511020,0.509050,0.506650,0.504150,0.502350

In [14]:
df_abs.head()

,862.13,863.88,865.63,867.38,869.13,870.88,872.63,874.38,876.13,877.88,...,1747.63,1749.38,1751.13,1752.88,extra_info,filename,sample_name,sample_date,run_number,process_method
0,0.001,0.001,0.001,0.000746,0.00000,0.09804,0.23904,0.22139,0.22554,0.24124,...,0.28247,0.28147,0.28053,0.27958,File: Users\stell\Desktop\StellarDat\South 18...,South 18 - 7-8-20 #1.ABS,south 18,2020-07-08 00:00:00,1,
0,0.001,0.001,0.001,0.088220,0.37437,0.32127,0.17101,0.15918,0.16184,0.17219,...,0.20912,0.20875,0.20827,0.20764,File: Users\stell\Desktop\StellarDat\South 16...,South 16 - 7-8-20-20 #1.ABS,south 16,2020-07-08 20:00:00,1,
0,0.001,0.001,0.001,0.000746,0.00000,0.10764,0.25807,0.24305,0.24577,0.25723,...,0.29995,0.29980,0.29959,0.29915,File: Users\stell\Desktop\StellarDat\South 2 ...,South 2 - 7-8-20-20 #2.ABS,south 2,2020-07-08 20:00:00,2,
0,0.001,0.001,0.001,0.000746,0.00000,0.10400,0.25080,0.23672,0.23925,0.25092,...,0.28670,0.28666,0.28670,0.28635,File: Users\stell\Desktop\StellarDat\South 17...,South 17 (Ground) - 7-8-20-20 #1.ABS,south 17,2020-07-08 20:00:00,1,ground
0,0.001,0.001,0.001,0.097632,0.46666,0.55056,0.44727,0.43291,0.43860,0.45731,...,0.50545,0.50380,0.50198,0.50045,File: Users\stell\Desktop\StellarDat\Raw - Co...,Hampton Coulter - 6-15-20 #1.ABS,hampton coulter,2020-06-15 00:00:00,1,